USE [Pos_Server_History]
GO

/****** Object:  Table [dbo].[NewVocDtl]    Script Date: 12/28/2016 09:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[NewVocDtl](
	[V_CODE] [char](1) NOT NULL,
	[V_NO] [char](11) NOT NULL,
	[V_DESC] [varchar](50) NULL,
 CONSTRAINT [PK_NewVocDtl_1] PRIMARY KEY CLUSTERED 
(
	[V_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

